<?php

namespace Tomazi\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NavigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationRepository extends EntityRepository
{
}
